# roles/mariadb/tasks/main.yml
---
- hosts: localhost
  tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "../vars/RedHat.yml"
      tags: mariadb

    - include_tasks: install.yml
    - include_tasks: config.yml
    - include_tasks: root-password.yml
    - include_tasks: databases.yml
    - include_tasks: users.yml
